# Explain basic idea behind hash table with suitable example.

"""
Hash tables are a type of data structure in which the address or the index value of the data element is generated from a hash function.
That makes accessing the data faster as the index value behaves as a key for the data value.
In other words Hash table stores key-value pairs but the key is generated through a hashing function.

So the search and insertion function of a data element becomes much faster as the key values theemselves become the index of the array which stores the data.

In Python, the Dictionary data types represent the implementation of hash tables. The keys in the dictionary satisfy the following requirements.
- The keys of the dictionary are hashable i.e. they are generated by hashing function which generates unique result for each unique value supplied to the hash function.
- The order of data elements in a dictionary is not fixed.
"""

# Declare a dictionary
dict = {'Name': 'Jon', 'Age': 7, 'Class': 'First'}

# Accessing the dictionary with its key
print(f"dict['Name']: {dict['Name']}")
print(f"dict['Age']: {dict['Age']}")
